# Generated by Django 5.2.8 on 2025-11-27 04:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='audio_file',
            field=models.FileField(upload_to='consultations/audio/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav', 'ogg', 'webm', 'm4a'])]),
        ),
    ]
